import openreview
import client_object
import sys

if sys.argv[1] == "1":
    print("posting")

client = client_object.client
venue_id = client_object.venue_id

ac_profiles = ["~Ruofeng_Yang1",
"~Yi_DONG7",
"~Jaime_Arias1",
"~Xiangyu_Liu4",
"~Andreas_Niskanen1",
"~Alexander_David_Rodriguez1",
"~Christian_Cabrera1",
"~Flavio_Oquendo1",
"~Sven_Hartmann1",
"~Alessandro_Burigana1",
"~Antonio_Bucchiarone1",
"~Thomas_C._Carroll1",
"~Jean-Paul_Jamont1",
"~Yi_Zheng18",
"~Carlos_Diaz_Alvarenga1",
"~Giacomo_Como1",
"~Chinmay_Sonar1",
"~Nic_Wilson1",
"~Zichun_Zhong1",
"~Sarah_Kiden1",
"~Christophe_GUETTIER1",
"~YAN_ZHENG1",
"~Chairi_Kiourt1",
"~Jinhao_Liang1",
"~Anson_Kahng1",
"~Atil_Iscen1",
"~Youssouf_OUALHADJ1",
"~Houyu_Zhou1",
"~Cassia_Trojahn1",
"~Junlin_Wu2",
"~Adina_Magda_Florea2",
"~Hannes_Högni_Vilhjálmsson1",
"~Frits_de_Nijs1",
"~Anna_Gautier1",
"~Rem_W._Collier1",
"~Michael_Schumacher1",
"~Hui_Fang7",
"~Piyush_Karande1",
"~Junichi_Suzuki1",
"~Qin_Yang2",
"~Jamal_Bentahar2",
"~Rik_Sengupta1",
"~Hirotaka_Ono1",
"~Mohamed_Tahar_Bennai1",
"~Maurice_Pagnucco1",
"~Fernando_Santos_Osório1",
"~Yu_Zhou26",
"~Adrian_Agogino1",
"~Kaiqi_Zhao2",
"~Ladislau_Boloni1",
"~Nadin_Kökciyan1",
"~Fred_Charles1",
"~Athirai_Aravazhi_Irissappane2",
"~Jacopo_Panerati1",
"~Samuel_H._Christie_V1",
"~Juan_Carlos_Nieves1",
"~Matteo_Baldoni1",
"~Soumajyoti_Sarkar1",
"~Anaëlle_Wilczynski1",
"~Sai_Ganesh_Nagarajan1",
"~Tingting_Li4",
"~Indrajit_Saha1",
"~Atsushi_Iwasaki1",
"~Ramasuri_Narayanam2",
"~Yves_Lesperance1",
"~Claudia_Szabo1",
"~Filipe_Saraiva1",
"~Jeffrey_O._Kephart1",
"~Calarina_Muslimani1",
"~Frédéric_Amblard2",
"~Dongmo_Zhang1",
"~Ian_A._Kash1",
"~Zita_Vale1",
"~Vivek_Nallur1",
"~Conor_Muldoon1",
"~Guangliang_Li2",
"~Artur_Niewiadomski1",
"~Evandro_de_Barros_Costa1",
"~Fengshuo_Bai1",
"~Chuxiong_Sun2",
"~Tien_Anh_Mai1",
"~Alan_Davoust1",
"~James_Patrick_Bailey1",
"~Yiqun_Chen3",
"~Marcos_de_Oliveira1",
"~Aron_Laszka1",
"~Tianpei_Yang1",
"~Monica_Tirea1",
"~Tiep_Le2",
"~Ayush_Chopra1",
"~Costin_Badica1",
"~Karissa_Jelonek1",
"~Dariusz_Barbucha1",
"~Ethan_H_Blaser1",
"~Ayan_Mukhopadhyay1",
"~Alessandro_Sapienza1",
"~Fuyuki_Ishikawa2",
"~Joris_Hulstijn1",
"~Paulo_Novais1",
"~Tomer_Ezra2",
"~Davide_Calvaresi1",
"~Yue_Zhang32",
"~João_M._C._Sousa1",
"~Corrado_Santoro1",
"~Sergio_Alvarez-Napagao1",
"~Emmanouil_S._Rigas1",
"~Stefania_Monica1",
"~Sukankana_Chakraborty1",
"~Alfredo_Garro1",
"~Kai_Jin3",
"~Esra_Erdem1",
"~Yì_N._Wáng2",
"~Trung_Thanh_Nguyen2",
"~Kazunori_Terada2",
"~Zun_Li1",
"~Roi_Yehoshua1",
"~Zilong_Wang2",
"~Gregory_J_Stein1",
"~Wei_Pan2",
"~Tuan_Quang_Dam1",
"~Ayal_Taitler1",
"~Christophe_Grand1",
"~Meghna_Lowalekar1",
"~Eduardo_Aoun_Tannuri1",
"~Charalampos_Kleitsikas1",
"~Kamel_Barkaoui1",
"~Rajith_Vidanaarachchi1",
"~Matthias_Klusch1",
"~Mark_A_Post1",
"~Dell'Acqua_Pierangelo1",
"~Shih-Fen_Cheng1",
"~Antonino_Rotolo2",
"~Eduardo_Mena1",
"~Thanh_Vinh_Vo2",
"~Goreti_Marreiros1",
"~Mourya_Thummalapeta1",
"~Jingqing_Ruan1",
"~Daniel_Halpern1",
"~Marie_Farrell1",
"~Jiahao_Chen9",
"~Weiran_Shen1",
"~Antoine_Zimmermann1",
"~Gautham_Das2",
"~HANG_YU7",
"~Chengguang_Xu1",
"~Elias_Fernández_Domingos2",
"~Xavier_Parent2",
"~Aurélie_Beynier2",
"~Koen_Kok1",
"~Cesar_Augusto_Tacla1",
"~Ting_Liu28",
"~Giovanni_Sartor1",
"~Paritosh_Verma1",
"~Diodato_Ferraioli1",
"~Joanna_Olszewska1",
"~Roland_Yap1",
"~Sylvie_Doutre1",
"~Youpeng_Zhao2",
"~Christos_Dimitrakakis1",
"~Shuo_Chen12",
"~Gregory_Kehne1",
"~Elia_Pacioni1"
]

# Create a dictionary with profile_id : [subject_area]
for ac in ac_profiles:
    print(ac + " Sending Message")
    subject = 'AAMAS 2026 Review Check In'
    message = 'Dear {{fullname}}, \n\n The AAMAS review system currently shows that you have completed none of the reviews assigned to you.  Can you please check in by emailing louise.dennis@manchester.ac.uk to confirm that you are aware that the review deadline is this Friday, 14th November, and that you anticipate being able to complete your review assignment by that deadline.\n\n  All the best,\n\n Louise and Chris'
    recipients = [ac]
    invitation = f'{venue_id}/-/Edit'
    if sys.argv[1] == "1":
        client.post_message(subject, recipients, message, invitation=invitation)

